### PR TITLE
Hh mark

### PR DESCRIPTION
**Pull request by MarkTA**

### CODE REVIEW

**Comment by zeekay** [comment]
Deploy preview ready!

Built with commit 79fe37067f9b07465dc6ccf5c52fcce87c80ab3a

http://deploy-preview-64.ludela.netlify.com

**Comment by zeekay** [comment]
Still wip?

**Comment by zeekay** [comment]
Description of changes?

**Comment by MarkTA** [comment]
This is ready to merge. I replaced the footer bar on all pages and removed the mobile animation on the about page story line.

**Pull request merged**
