### PR TITLE
Latest changes to /tech

### PR DESCRIPTION
**Pull request by petealbertson**
Key changes:
- removing steps 6 and 7
- update header to match new home page
- updates for mobile landscape mode

### CODE REVIEW

**Comment by zeekay** [comment]
Deploy preview ready!

Built with commit 16009c1f64e1bd9ef66bb4a33d41568336cfa8b1

http://deploy-preview-103.ludela.netlify.com

**Comment by davidtai** [comment]
Tech page behaves much better.  However hte menu css is broken on the faq and legal pages.

**Comment by petealbertson** [comment]
@davidtai the menu css is fixed. I'm afraid there's not much we can do about the iOS overlay spazz - when safari switches to minimal-ui it triggers a resize which causes scrollify to reset the slide. I adjusted the overlay to always reveal a little at the bottom so it doesn't completely disappear on reset. It's less jarring that way but I'm not sure we can get rid of it altogether.

**Comment by petealbertson** [comment]
Blocked by https://github.com/ludela/ludela.com/pull/105

**Comment by petealbertson** [comment]
@davidtai / @zeekay ready for merge

**Pull request merged**
