### PR TITLE
Header update

### PR DESCRIPTION
**Pull request by MarkTA**
Header and cta update across about and general pages. This branch includes animation fixes and resolves merge conflicts from the branch "Mark".

### CODE REVIEW

**Comment by zeekay** [comment]
Deploy preview ready!

Built with commit ca3d4fac43c0a064fbb49eb0a8680de5d60efd6d

http://deploy-preview-98.ludela.netlify.com

**Comment by MarkTA** [comment]
@davidtai this PR also includes animation fixes for about page (including mobile updates). Merge or close PR #96 before merging this one.

**Comment by davidtai** [comment]
Has this bug https://github.com/ludela/ludela.com/issues/102

**Comment by davidtai** [comment]
- 'about us' tends to reset to the top on ios simulator for whatever reason
- can we change 'preorder now' to say 'shop now' and link to /shop

**Pull request merged**
